# Generated by Django 5.0.2 on 2024-02-18 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/products"
                    ),
                ),
                ("discount", models.IntegerField()),
                (
                    "create_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024,
                            2,
                            18,
                            23,
                            55,
                            56,
                            742125,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("published_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
